language: php
git:
  depth: 5

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: TYPO3_VERSION=9.5.*
    - php: 7.1
      env: TYPO3_VERSION=9.5.*
    - php: 7.2
      env: TYPO3_VERSION=9.5.*
  allow_failures:
    - php: nightly
      env: TYPO3_VERSION=9.5.*

cache:
  directories:
    - $HOME/.composer/cache


before_install:
  - phpenv config-rm xdebug.ini || echo "xdebug not available"

install:
  - composer require typo3/cms="$TYPO3_VERSION" --dev
  - composer install --no-progress --no-suggest -n

script:
  - ./vendor/bin/grumphp run
  - composer test
