language: php
git:
  depth: 5

matrix:
  fast_finish: true
  include:
    - php: 7.4
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache


before_install:
  - phpenv config-rm xdebug.ini || echo "xdebug not available"

install:
  - composer install --no-progress --no-suggest -n

script:
  - ./vendor/bin/grumphp run
