services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Pluswerk\Sentry\Service\:
    resource: '../Classes/Service/*'
    public: true

  Pluswerk\Sentry\Queue\:
    resource: '../Classes/Queue/*'

  Sentry\Options:
    public: true

  Sentry\Serializer\PayloadSerializer:
    public: true

  Sentry\Serializer\PayloadSerializerInterface:
    alias: Sentry\Serializer\PayloadSerializer
    public: true

  Pluswerk\Sentry\Queue\QueueInterface:
    alias: Pluswerk\Sentry\Queue\FileQueue
    public: true

  Pluswerk\Sentry\Queue\FileQueue:
    arguments:
      # 0 for no limit, positive integer to limit the files created in the queue
      $limit: 10000
      $compress: true

  Pluswerk\Sentry\Command\FlushCommand:
    tags:
      - name: 'console.command'
        command: 'pluswerk:sentry:flush'
        description: 'Transports potentially queued events'

  TYPO3\CMS\Frontend\ContentObject\Exception\ProductionExceptionHandler:
    class: Pluswerk\Sentry\Handler\ContentObjectProductionExceptionHandler
    public: true
    shared: false
