parameters:
  env(SENTRY_ENABLED): 'true'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Pluswerk\Sentry\ScopeConfig:

  Pluswerk\Sentry\Sentry:
    arguments:
      - '@Pluswerk\Sentry\ScopeConfig'
      - '@TYPO3\CMS\Core\Configuration\ExtensionConfiguration'
      - '%env(SENTRY_DSN)%'
      - '%env(SENTRY_ENABLED)%'
