services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  Pluswerk\Sentry\Service\:
    resource: '../Classes/Service/*'
    public: true
  Pluswerk\Sentry\Queue\:
    resource: '../Classes/Queue/*'
  Sentry\Options:
    public: true
  Sentry\Serializer\PayloadSerializer:
    public: true
  Sentry\Serializer\PayloadSerializerInterface:
    alias: Sentry\Serializer\PayloadSerializer
    public: true
  Pluswerk\Sentry\Queue\QueueInterface:
    alias: Pluswerk\Sentry\Queue\FileQueue
    public: true
  Pluswerk\Sentry\Queue\FileQueue:
    arguments:
      $limit: 10000
      $compress: true
  Pluswerk\Sentry\Command\FlushCommand:
    tags:
      -
        name: console.command
        command: 'pluswerk:sentry:flush'
        description: 'Transports potentially queued events'
  pluswerk.sentry.original.contentObject.productionExceptionHandler:
    class: TYPO3\CMS\Frontend\ContentObject\Exception\ProductionExceptionHandler
  TYPO3\CMS\Frontend\ContentObject\Exception\ProductionExceptionHandler:
    class: Pluswerk\Sentry\Handler\ContentObjectProductionExceptionHandler
    public: true
    shared: false
    arguments:
      $productionExceptionHandler: '@pluswerk.sentry.original.contentObject.productionExceptionHandler'
  Pluswerk\Sentry\EventListener\ConsoleErrorEventListener:
    tags:
      -
        name: event.listener
        identifier: pluswerk/sentry/console-error-event-listener
        event: Symfony\Component\Console\Event\ConsoleErrorEvent
